<?php

namespace App\Repositories\ReportReasonRepo;

use App\Models\ReportReason;
use App\Models\User;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Collection;
use TimWassenburg\RepositoryGenerator\Repository\BaseRepository;

/**
 * Class reportReasonRepo.
 */
class ReportReasonRepo extends BaseRepository implements ReportReasonRepoInterface
{

    protected $reportReason;
    public function __construct(ReportReason $reportReason)
    {
        $this->reportReason = $reportReason;
        parent::__construct($reportReason);
    }

    public function paginate($limit = null, array $with = [], $columns = ['*'])
    {
        return parent::paginate($limit, $with, $columns); // TODO: Change the autogenerated stub
    }

    public function all(array $with = [], array $paramsSelect = ['*'], array $condition = []): Collection
    {
        return parent::all($with, $paramsSelect, $condition); // TODO: Change the autogenerated stub
    }

    public function create(array $attributes): Model
    {
        return parent::create($attributes); // TODO: Change the autogenerated stub
    }

    public function delete(string $id)
    {
        return parent::delete($id); // TODO: Change the autogenerated stub
    }

    public function update(string $id, array $attributes): bool
    {
        return parent::update($id, $attributes); // TODO: Change the autogenerated stub
    }

    public function find(string $id, array $with = [], array $params = []): ?Model
    {
        return parent::find($id, $with, $params); // TODO: Change the autogenerated stub
    }

    public function findWithTrash(string $id): ?Model
    {
        return parent::findWithTrash($id); // TODO: Change the autogenerated stub
    }

    public function findByField(array $columns, string $keyword, $limit = null, array $with = [])
    {
        return parent::findByField($columns, $keyword, $limit, $with); // TODO: Change the autogenerated stub
    }


}
